name: RSaalfeld
theme: jekyll-theme-minimal
title: Robison Saalfeld Portfolio
description: My personal portfolio of data science projects


navigation:
  - title: Home
    url: /
  - title: About
    url: /about.html
